validator-labs/validatorctl

go.mod, pkg/config/config.go, pkg/logging/logger.go, pkg/services/k8s_service.go
https://github.com/validator-labs/validatorctl/issues/4
Removing all dead code from the repo
=> chore: remove dead code

pkg/cmd/common/common.go, pkg/config/constants.go, pkg/logging/logger.go
https://github.com/validator-labs/validatorctl/issues/6
Further simplify the validatorctl by removing the loggers ability to write to disk
=> chore: remove loggers ability to write to disk

Makefile, cmd/root.go, pkg/cmd/common/common.go, pkg/cmd/validator/validator.go, pkg/utils/embed/embed.go, pkg/utils/exec/exec.go, pkg/utils/kind/kind.go, pkg/utils/kube/kube.go
https://github.com/validator-labs/validatorctl/issues/2
- Updates Makefile to not install binary dependencies (docker, helm, kind, kubectl), unless the test job is being run from gha
- Update CLI to verify that users already have these dependencies installed
- If any binary is not installed, print an error message with the missing binary and exit
=> feat: ensure no binaries are embedded with validatorctl

pkg/cmd/validator/validator.go, pkg/utils/string/string.go, tests/integration/_validator/executor.go, tests/integration/_validator/testcases/data/validator.yaml, tests/integration/_validator/testcases/test_validator.go, tests/integration/common/single_func_test_case.go, tests/integration/suite_test.go
Ensures that the integration test suite passes when executed against a non-dev (AKA release) CLI version.
- properly propagates global test suite context into each test suite, rather than initializing new test contexts in various places
- dynamically constructs mock TUI values based on CLI version
=> refactor: ensure int. tests succeed w/ a non-dev CLI version

go.mod, pkg/cmd/validator/validator.go, pkg/components/network.go, pkg/components/oci.go, pkg/components/validator.go, pkg/components/vsphere.go, pkg/config/constants.go, pkg/config/manager/config_manager.go
Setup the following helper functions to easily configure vsphere, oci, and network validator plugins and to generate the validator config file:
- ConfigureBaseValidator(...)
- ConfigureVspherePlugin(...)
- ConfigureNetworkPlugin(...)
- ConfigureOciPlugin(...)
- Ensured `ConfigFile` and `ValidatorConfigFile` are not both `validator.yaml`. `ConfigFile` is now `validatorctl.yaml`
- Ensure that the `/bin` base dir is never created. This is not needed because `validatorctl` does not install the helm/docker/kubectl/kind binaries
=> feat: add helpers to easily configure validator plugins

README.md, docs/subcommands.md, pkg/config/versions.go, tests/integration/_validator/testcases/data/validator.yaml
N/A
This PR adds a documentation page that goes into greater detail about each subcommand.
=> docs: added subcommands docs page

cmd/root.go, cmd/validator.go, go.mod, go.sum, pkg/cmd/validator/validator.go, pkg/logging/logger.go, pkg/services/validator/vmware.go, pkg/utils/embed/embed.go, pkg/utils/embed/resources/validator/docs.tmpl, pkg/utils/kind/kind.go
Resolves #109
Resolves #98
Add `validatorctl docs` command to display supported versions of validator & validator plugins.
Sample output:
Requires:
- https://github.com/validator-labs/validatorctl/pull/110
=> feat: add docs command; refactor to use embeddedfs pkg

go.mod, go.sum, pkg/components/validator.go, pkg/services/validator/aws.go, pkg/services/validator/aws_test.go, pkg/services/validator/common.go, pkg/services/validator/network.go, pkg/services/validator/network_test.go, pkg/services/validator/vmware_test.go, tests/integration/_validator/testcases/test_validator.go
Resolves #112
Add support for reading AMIRules & HTTPFileRules. Also read CA certificates for network plugin rules.
Requires:
- https://github.com/spectrocloud-labs/prompts-tui/pull/7
=> feat: read CA certs for network rules, add HTTPFileRules, AMIRules

cmd/validator.go, pkg/cmd/validator/validator.go, pkg/config/config.go, pkg/services/validator/validator_service.go, tests/integration/_validator/testcases/test_validator.go
The proposal of this PR is to simplify our command API by reducing the number of flags we have and using the same flags in different commands.
Namely, this PR focuses on the `--silent` and `--reconfigure` flags. Instead of having both flags available for the `NewInstallValidatorCmd` and `NewConfigureValidatorCmd`, we can reduce to just using the `--reconfigure` flag in both commands.
The implications of these changes are this:
1. No flags passed in => interactive mode
2. If only `-f` is used in either the Install or Configure command => silent mode (ie no TUI prompts)
3. If `-f` and `-r` are used in conjuncture in either the Install or Configure command => reconfigure mode (interactive but with defaults from the config provided to users)
4. If a user runs the install and configure …
=> refactor: remove -s flag

cmd/root.go, cmd/validator.go, pkg/cmd/validator/validator.go, pkg/config/config.go, pkg/config/versions.go, tests/integration/_validator/testcases/data/validator.yaml, tests/integration/_validator/testcases/test_validator.go
N/A
Add `rules` subcommand with `apply` and `check` subsubcommands to differentiate the application of validator rule CRs vs. direct rule evaluation.
=> refactor: add rules subcommand & split out apply/check

cmd/root.go, cmd/validator.go, go.mod, pkg/cmd/validator/validator.go, pkg/config/constants.go, pkg/logging/logger.go, tests/integration/_validator/testcases/test_validator.go, tests/integration/common/cli_commands.go
Resolves #138 
- Set exit code 2 for `validator rules check` if validation fails for any rule.
- Document exit codes.
- Re-enable logging to disk under unique log directory per `validatorctl` execution.
=> feat: set exit code 2 on validation failure; restore debug log file

pkg/cmd/validator/validator.go, pkg/services/clouds/maas_service.go, pkg/services/validator/aws.go, pkg/services/validator/azure.go, pkg/services/validator/maas.go, pkg/services/validator/network.go, pkg/services/validator/oci.go, pkg/services/validator/validator_service.go, pkg/services/validator/vmware.go, tests/integration/_validator/testcases/test_validator.go
N/A
Sometime during the CLI refactor, the E2E flow for prompting users for installation & rule config in a single pass in config-only mode was broken. This PR fixes that and addresses various issues with integration test prompting and dummy values that were previously missed as a result of the broken TUI flow.
=> fix: correct TUI flow for `validator install -o --apply`

pkg/cmd/validator/validator.go
N/A
When running `validator rules check`, we werent properly setting the validationSuccess variable (ok) to false.
=> fix: ensure ErrValidationFailed is returned for maas direct validation failures

pkg/utils/embed/resources/validator/validator-base-values.tmpl
MAAS auth was present 2 times in the base values template. Deleting the out-of-order template.
=> fix: remove duplicate maas base values from template

cmd/validator.go, pkg/cmd/validator/validator.go, pkg/services/validator/validator_service.go, pkg/utils/exec/exec.go
N/A
Fixes a bug where docker and kind were considered mandatory even when using an existing k8s cluster.
Verify binaries and exit as early as possible if appropriate.
=> fix: only require docker, kind when provisioning kind cluster

pkg/components/validator.go, pkg/services/validator/azure.go, tests/integration/_validator/testcases/test_validator.go
Resolves #124
Adds prompts for the Azure community gallery image rule which lets users verify that a particular community image gallery exists within a particular subscription. If it exists, it is accessible by any security principal and Azure system because community image galleries are public.
Also refactors Azure plugin related code to be more like other plugins. Same structure for prompting and no more "RBAC rule type" which must be encoded in the config file and taken into account when re-configuring.
=> feat: support Azure plugin community gallery image rule

pkg/cmd/validator/validator.go, pkg/components/validator.go, pkg/config/versions.go, tests/integration/_validator/testcases/data/validator.yaml
Resolves https://github.com/validator-labs/validatorctl/issues/188
Ensures we dont panic when executing `validator rules check -f config.yaml` without all plugins defined
=> fix: support `validator rules check -f config.yaml` without all plugins defined

go.mod, go.sum, hack/validator.tmpl, pkg/cmd/validator/validator.go, pkg/components/validator.go, pkg/config/versions.go, pkg/services/validator/vmware.go, pkg/services/validator/vmware_test.go, pkg/utils/embed/resources/validator/validator-base-values.tmpl, tests/integration/_validator/testcases/data/validator.yaml
Resolves #183 
Removing `VspherePluginConfig.Account` and switching to using `.Auth.CloudAccount`, to align with updates to the plugin.
=> refactor: move vsphere account under auth to match new plugin api

pkg/cmd/validator/validator.go, pkg/components/validator.go
=> fix: handle validation errors, result count mismatch

go.mod, go.sum, pkg/config/versions.go, pkg/services/validator/validator_service.go, pkg/services/validator/vmware.go, tests/integration/_validator/testcases/data/validator.yaml
N/A
- Filter empty lines and comments from vCenter local file privileges
- Skip `KUBECONFIG` check when updating passwords in direct mode
=> fix: filter vCenter local file privileges properly, skip KUBECONFIG check when updating passwords in direct mode

cmd/validator.go, go.mod, pkg/cmd/validator/validator.go, pkg/cmd/validator/validator_test.go, pkg/config/config.go, pkg/config/constants.go, pkg/config/versions.go, pkg/utils/file/file.go, pkg/utils/file/file_test.go, tests/integration/_validator/testcases/data/validator-crs/combined.yaml, tests/integration/_validator/testcases/data/validator-crs/network/network.yaml, tests/integration/_validator/testcases/data/validator-crs/oci/oci.yaml, tests/integration/_validator/testcases/data/validator.yaml, tests/integration/_validator/testcases/test_validator.go
Resolves https://github.com/validator-labs/validatorctl/issues/178
Resolves https://github.com/validator-labs/validatorctl/issues/136
This PR adds support for passing in custom resource documents to the `validator rules check` command via the `--custom-resources` flag. The `--custom-resources` flag can receive either a path to a directory or to a file. 
If a directory path is provided, we check each file within the directory for CR documents. Note that we walk the entire file tree from a particular directory. This means that users are able to organize their CRs in a manner like this:
```
❯ tree tests/integration/_validator/testcases/data/validator-crs
tests/integration/_validator/testcases/data/validator-crs
├── combined.yaml
├── network
│   └── network.yaml
└── oci
└── oci.yaml
3 …
```
=> feat: add --custom-resources flag to validator rules check as an alternate to -f

cmd/validator.go, pkg/cmd/validator/validator.go, pkg/config/versions.go, tests/integration/validatorctl/testcases/data/validator.yaml
N/A
Breaks the `ConfigureOrCheckCommand` function down into a `ConfigureCommand` function and a `CheckCommand` function. Also introduces a new `configureValidatorConfig` helper function.
With this change, the cognitive load of modifying either the `ConfigureCommand` or `CheckCommand` functions should be reduced because we no longer need to keep both direct evaluation and continuous evaluation in mind.
=> refactor: split ConfigureOrCheckCommand into multiple functions

pkg/cmd/validator/validator.go
N/A
We pre-populate `ValidationRuleErrors` with nils and update them by index in `Finalize`. Therefore we need to ignore nils 🤦🏼
=> fix: ignore nil errors in validationResponseOk

pkg/config/versions.go, tests/integration/validatorctl/testcases/data/validator.yaml
Uses `make reviewable` to update plugins to the latest version. We do not yet have this automated.
=> chore: update plugin versions

pkg/config/versions.go, pkg/utils/string/string.go, tests/integration/validatorctl/testcases/data/validator.yaml
Our Revive linter is disallowing the name `len` for a parameter. We made this code a while ago, but the linter is raising the issue now. It may be an update to the linter. This changes the parameter name to resolve it.
Also applies changes from latest `make reviewable` so that the PR can be merged.
=> fix: param name of util function (for linter)

pkg/config/versions.go, pkg/utils/crypto/crypto.go, pkg/utils/embed/resources/validator/validator-base-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-aws-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-azure-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-maas-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-network-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-oci-values.tmpl, pkg/utils/embed/resources/validator/validator-plugin-vsphere-values.tmpl, tests/integration/validatorctl/testcases/data/validator.yaml
Resolves #276 
Following the removal of `kube-rbac-proxy` from all plugins and validator, this PR bumps all versions and updates the chart templates to remove `kube-rbac-proxy`
Manually tested by installing validator and all plugins, and confirming that all controllers come up, and metrics service is exposed and accessible with `curl`.
=> chore: update chart values to remove kube-rbac-proxy
